Module8 task1
htmlacademy-ecmascript/1556343-cinemaddict-15 pull request #14
Opened 2021-09-21 16:57 UTC by alisaspl

2021-09-21 17:17 UTC, bbalkonsky commented
@alisaspl убери открытие случайной страницы. пусть сначала всегда открывается раздел All movies с сортировкой by default

2021-09-21 17:40 UTC, bbalkonsky requested changes

2021-09-21 17:40 UTC, bbalkonsky commented on src/view/film-comment.js
>              <span class="film-details__comment-day">${dayjs().from(dayjs(this._comment.date))}</span>
Дата комментария отображается в формате год/месяц/день часы:минуты (например «2019/12/31 23:59»).

2021-09-21 17:40 UTC, bbalkonsky commented on src/view/film-comment.js
> +          <p class="film-details__comment-text">${he.escape(he.unescape(this._comment.comment))}</p>
ты уже экранировала комментарий на этапе отправки на сервер. нет необходимости производить какие либо манипуляции во время получаения

2021-09-21 17:40 UTC, bbalkonsky commented on src/mocks.js
> +const filmListData = new Array(3).fill().map(() => generateFilmData());
этот файл тебе еще нужен?

2021-09-21 17:41 UTC, alisaspl commented on src/view/film-comment.js
>              <span class="film-details__comment-day">${dayjs().from(dayjs(this._comment.date))}</span>
Это из дополнительного задания: реализуйте вывод даты публикации комментария в человеческом формате (например «now», «a few minutes ago», «8 years ago» и т. д.) вместо формата, предложенного в пункте 1.4 техзадания.

2021-09-21 17:43 UTC, alisaspl commented
> @alisaspl убери открытие случайной страницы. пусть сначала всегда открывается раздел All movies с сортировкой by default

В сборке сейчас открывается именно так

2021-09-21 17:57 UTC, bbalkonsky commented on src/view/film-comment.js
>              <span class="film-details__comment-day">${dayjs().from(dayjs(this._comment.date))}</span>
Точно. Проверял только на основную часть, забыл об этом

2021-09-22 06:50 UTC, bbalkonsky commented
@alisaspl давай, 2 микроизменения и можно публиковать (я так понял, последнюю часть ты выполнять не планируешь?)

2021-09-22 08:48 UTC, alisaspl commented
> @alisaspl давай, 2 микроизменения и можно публиковать (я так понял, последнюю часть ты выполнять не планируешь?)

Хотела уже в защите доделать 9 часть, можно так ?

2021-09-22 09:29 UTC, merged