create views
htmlacademy-ecmascript/1556343-cinemaddict-15 pull request #3
Opened 2021-08-04 09:17 UTC by alisaspl

2021-08-04 11:01 UTC, bbalkonsky requested changes
во всех файлах отступы бы поправить.
и я не понял, в чем именно вопрос с комментарием // FIXME, можно подробнее? (мой тг или почта всегда открыты).

а вообще неплохо, так держать

2021-08-05 05:21 UTC, alisaspl commented on public/index.html
> +  <slot id="menu-slot"></slot>
Изначально использовала вашу разметку, 
но при такой разметке некоторые теги section, например ```<section class="statistic">```, 
создавали большие лишние отступы.

Как лучше поступить ?

2021-08-05 05:44 UTC, bbalkonsky commented on public/index.html
> +  <slot id="menu-slot"></slot>
это нормально. сейчас мы рендерим все в кучу, но в будущем это будут разные страницы. 
в данном задании цель - просто поделить на компоненты

2021-08-05 15:14 UTC, bbalkonsky commented
еще правки ожидаются?
вижу, что замечания исправлены (ну почти), но повторно на проверку отправлено не было

2021-08-05 15:38 UTC, merged