popup escape & empty view
htmlacademy-ecmascript/1556343-cinemaddict-15 pull request #6
Opened 2021-08-20 09:55 UTC by alisaspl

2021-08-20 10:53 UTC, bbalkonsky requested changes
на счет проблемы с отрисовкой фильмов, если их меньше 5:
чтобы отлавливать такие вещи в будущем - лучше генерировать случайное количество фильмов, а не быть привязанным к одному числу

а еще, меня расстраивает, что ты не хочешь делать дополнительное задание (блоки топ по каментам и топ по просмотрам), у тебя отлично все получается, а эта часть не такая сложная (там просто сделать пару раз то, что ты и так уже делала для цифр фильтров в меню). талант пропадает ;)

2021-08-20 10:53 UTC, bbalkonsky commented on src/main.js
>  //import StatisticsView from './view/statistics';
Б18. В коде проекта нет файлов и частей кода, которые не используются, включая закомментированные участки кода.

2021-08-20 10:53 UTC, bbalkonsky commented on src/view/film-list.js
> +        this._element = utils.createElement(this.getEmptyTemplate());
если смотреть по макетам - кнопок сортировки в данном случае быть не должно
![image](https://user-images.githubusercontent.com/19642441/130220019-fd5b1fcd-a396-4c40-9975-ec3492dce8ca.png)

2021-08-20 10:53 UTC, bbalkonsky commented on src/main.js
>  const mockData = {
я бы предложил всю логику генерации фальшивых данных вынести в другое место (в utils или mock.js), а в Main.js только оперировать этими данными

2021-08-20 10:53 UTC, bbalkonsky commented on src/view/film-list.js
> +        const filmExtraMostCommentedView = new FilmExtraMostCommentedView([this._films[2], this._films[3]]);
что произойдет, если фильмов будет 1 или 2?

2021-08-20 10:53 UTC, bbalkonsky commented on src/view/film-list.js
> +          utils.renderElement(container, new FilmCardView(this._films[this._lastFilmIndex]).getElement());
что будет, если фильмов будет меньше 5?

2021-08-20 10:53 UTC, bbalkonsky commented on src/view/film-list.js
> +        for(; this._lastFilmIndex < 5; this._lastFilmIndex++) {
кстати, на счет цифры 5:
Б31. В коде не используются «магические значения», под каждое из них заведена отдельная переменная, названная как константа.

2021-08-20 17:24 UTC, alisaspl commented on src/view/film-list.js
> +        this._element = utils.createElement(this.getEmptyTemplate());
Не знаю как поступить, view списка фильмов должно создавать view сортировки, или меню должно создавать оба эти view. Проблема в том, что section sort-menu и section film-list оба в одном контейнере.

2021-08-21 05:46 UTC, bbalkonsky commented on src/view/film-list.js
> +        this._element = utils.createElement(this.getEmptyTemplate());
вьюшка сортировки вполне может быть внутри компонента списка фильмов. а вот меню, на мой взгляд, вообще никак не относится к списку фильмов, хоть у них и есть общие данные.

я бы еще вынес наружу логику, где ты определяешь, рисовать ли список фильмов или нет, так как это вообще не задача этого компонента. его цель - просто показать фильмы.

2021-08-22 10:02 UTC, bbalkonsky approved these changes
в film-list.js на строке 36, где ты вызываешь this.onShowMoreButtonClick() - решение, как по мне довольно красивое, но, возможно, спорное. переименуй его во что нибудь более нейтральное (вроде нарисоватьСледующуюПорциюФильмов), так оно станет осмысленнее и у других людей вопросов меньше будет =)

2021-08-22 10:03 UTC, merged