Module5 task1
htmlacademy-ecmascript/1556343-cinemaddict-15 pull request #8
Opened 2021-09-01 17:26 UTC by alisaspl

2021-09-02 17:09 UTC, bbalkonsky commented
нашел баг: если убрать, например, все фильмы из просмотренных и повторно перейти на фильтр по ним, то останется неработающая кнопка
![image](https://user-images.githubusercontent.com/19642441/131887304-5ec8a21f-180b-4be9-bca8-5bf06ef1a506.png)

2021-09-02 17:13 UTC, bbalkonsky commented
еще такой момент. это будет проверяться на финальной сдаче, но можно бы сделать уже сейчас. в тз есть пункт: 
При смене фильтра или переключении с экрана с фильмами на экран статистики и обратно сортировка сбрасывается на состояние «Sort by default».

2021-09-02 17:13 UTC, bbalkonsky requested changes
сразу обе части, плюс еще и вторая страница, так держать!

2021-09-02 17:13 UTC, bbalkonsky commented on src/presenter/film-list.js
> +          for(const key of this._filmPresenters.keys()) {
три почти одинаковые функции. может быть их можно как нибудь вынести в отдельный метод, где тип кнопки будет параметром?
кажется, где то тут у тебя уже такое даже было реализованно

2021-09-02 17:13 UTC, bbalkonsky commented on src/presenter/film-list.js
> +      {id: film.id, view},
а зачем ты ключом записываешь объект, а не просто айдишник?

2021-09-04 12:37 UTC, alisaspl commented on src/presenter/film-list.js
> +      {id: film.id, view},
Там хранятся не только view фильмов, но и view фильмов в блоках Top rated, Most commented и попапе, айди этих view начинают пересекаться.

2021-09-06 14:28 UTC, bbalkonsky commented
@alisaspl ты не поправила баг, о котором я написал в самом начале. мы можем договориться, что оно будет исправлено в следующем пулреквесте, либо можешь доделать сейчас. какой вариант тебе больше по-душе? :upside_down_face:

2021-09-07 12:17 UTC, alisaspl commented
В сборке комментарием выше правильно работает фильтр с нулевыми значениями и сортировка включается по умолчанию, как воспроизвести проблему?

2021-09-07 12:19 UTC, bbalkonsky commented
My bad, гитхаб в этот раз как то долго собирал, видимо. я раза 4 проверял и каждый раз проблема была

2021-09-07 12:19 UTC, merged